[[artifact]]
label = "lexicon_cli"
crate = "../../lexicon-cli"
artifact_output_path = "../../artifacts/"
type = "custom"

[[artifact]]
label = "lexicon_framework"
crate = "../../lexicon-framework"
artifact_output_path = "../../artifacts/"
type = "custom"

[[target]]
label = "linux-x86_64-musl"
os = "linux"
arch = "x86_64"
environment = "musl"

[[bundle]]
label = "lexicon"
crate = "../.."
artifact_output_path = "../../artifacts/"
type = "custom"
protocol = "cargo-embdedded-bundle-v0.1.0"
inputs = [
    "lexicon_cli",
    "lexicon_framework",
]