[[artifact]]
label = "lexicon_cli"
crate = "../../lexicon-cli"
artifact_output_path = "../../artifacts/"
type = "custom"
version = "0.1.0"

[[artifact]]
label = "lexicon_framework"
crate = "../../lexicon-framework"
artifact_output_path = "../../artifacts/"
type = "custom"
version = "0.1.0"

[[artifact]]
label = "lexicon_installer"
crate = "../../lexicon-installer"
artifact_output_path = "../../artifacts/"
type = "custom"
version = "0.1.0"

[[target]]
label = "linux-x86_64-musl"
os = "linux"
arch = "x86_64"
environment = "musl"


