[[artifact]]
label = # optional
manifest = <Relative path from making-rust-artifacts/ to Cargo.toml of the create the artifact will be build from> # mandatory
type = <Classification of artifact type, must be "release", "snapshot", or "custom"> # mandatory
version = <Version number> # mandatory
name = <File name of produced artifact, replacing name defined in either "[[bin]]" or "[[package]]" of manifest> # optional
exclude = <array of "label" value(s) from "[[target]](s)" to exclude the corresponding Target for this given artifact.> #optional

[[target]]
label =  # optional (unless you want to exclude this target for any artifact(s) in scope)
os = <Target OS for artifact(s) produced> # mandatory
arch = <Target architecture for artifact(s) produced> <user chooses, mandatory>
environment = <Target ABI/runtime/toolchain environment for artifact(s) produced (glibc, gnu, musl, etc.)> # optional


